### ISSUE TITLE
Tibialyzer might crash when taking screenshot on Rare Item Drop

### ISSUE THREAD

**Issue by Nopermoto** [Mytherin/Tibialyzer#32]
I've had three occurrences with Tibialyzer crashing, all have been during a item drop and I've had Tibialyzer set to Screenshot on Rare Item Drop.

************** Exception Text **************
System.InvalidOperationException: Object is currently in use elsewhere.
   at System.Drawing.TextureBrush..ctor(Image image, WrapMode wrapMode)
   at System.Windows.Forms.ControlPaint.DrawBackgroundImage(Graphics g, Image backgroundImage, Color backColor, ImageLayout backgroundImageLayout, Rectangle bounds, Rectangle clipRect, Point scrollOffset, RightToLeft rightToLeft)
   at System.Windows.Forms.Control.PaintBackground(PaintEventArgs e, Rectangle rectangle, Color backColor, Point scrollOffset)
   at System.Windows.Forms.Control.PaintBackground(PaintEventArgs e, Rectangle rectangle)
   at System.Windows.Forms.Control.OnPaintBackground(PaintEventArgs pevent)
   at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
   at System.Windows.Forms.Control.OnPrint(PaintEventArgs e)
   at System.Windows.Forms.Control.WmPrintClient(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

I left out the Loaded Assemblies.

**Comment by Mytherin** [comment]
I think I solved this with commit 5da2ce0d21f0014140db7d1c20d2763c933d1700, have you compiled the latest Tibialyzer version yourself or are you using a different version?

**Comment by Nopermoto** [comment]
Using the offical version 1.1.0, downloaded executable a few days ago. No changes done by me in any of the files.

Running .NET Framework 4.5.2

**Comment by Mytherin** [comment]
I've updated the beta release with the latest version, [here](https://github.com/Mytherin/Tibialyzer/releases/tag/1.2.0-beta). Try using that and see if it fixes this issue for you.

**Comment by mathiasbynens** [comment]
@Nopermoto Did the updated version solve your problem?

**Comment by Jacu93** [comment]
I didn't want to create new issue because it's related to screenshot module. I have an option to make a screenshot on level advance and on death. The problem is I get some random screenshot of my login screen named with "Advance" prefix. I'm not sure what it is but I think that it scans server log to fast and it detect advance during offline training before I can even see my character. It looks like that:
![advance - 2016-04-01 01h14m06s0460ms](https://cloud.githubusercontent.com/assets/18491485/14575868/0ffb8a88-0365-11e6-8cdf-7be8ec511e1e.png)

**Comment by GalLuvton** [comment]
Well, since memory-wise, you are currently connected (even if the GUI didn't catch up to it), I don't see a way to make it skip the login advances.
I think the options are:
- check if the previous message indicated that this is a login skill advance, and skip it
- have a short timer on logins (there is a memory cell saying if you are logged in or not, just check when it changes from false to true) and don't scan memory in that short time frame
- user side- just ignore those pictures

If you have any understanding of tibia's GUI structs, maybe you can poll one for visibility and go by that.
